version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install python packages
          command:
            pip install --user -r requirements.txt
      - run:
          name: Run unit test
          command: 
            python3 -m pytest
      - run:
          name: Run Flake8
          command:
            python3 -m flake8
      - run:
          name: Docker
          command:
            docker push kakashidota.azurecr.io/first/dockerimg:dev 
workflows:
  build_test:
    jobs:
      - run_tests